### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by darkorb** [yakumo-saki/docker-glitch-soc#9]
Looks like there are a few changes/updates needed to the `Dockerfile` as noted in https://github.com/yakumo-saki/docker-glitch-soc/issues/8#issuecomment-1720059819

That one got closed, but the `Dockerfile` part is still relevant and will need doing.

**Comment by yakumo-saki** [comment]
Thanks for notifing this.
I'll try to fix this today.

PS: Sorry for late reply.

**Comment by yakumo-saki** [comment]
Build is back to normal. Thank you @darkorb !
